# Generated by Django 2.1.2 on 2018-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_auto_20181024_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='supplies',
            field=models.CharField(default='No supplies needed right now,', help_text='Coma separated string of supplies', max_length=1000),
        ),
    ]
