# Generated by Django 2.1.2 on 2018-12-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0007_camps_supplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camps',
            name='photo',
        ),
    ]
