# Generated by Django 2.1.2 on 2018-12-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0008_remove_camps_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camps',
            name='user',
        ),
    ]
