# Generated by Django 2.1.2 on 2018-12-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectioncentres', '0004_collectioncentrestock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncentre',
            name='supplies',
            field=models.CharField(default='No supplies needed right now,', help_text='Coma separated string of supplies', max_length=1000),
        ),
    ]
